package com.example.demo.model;

import java.math.BigDecimal;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName= "bankAccounts")
public class BankAccount {
	
	@DynamoDBHashKey(attributeName =  "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String holder; //id del titular de la cuenta
	
	
	@DynamoDBAttribute
	private BigDecimal amount; // Saldo actual de la cuenta

	@DynamoDBAttribute
	private Date dateCreated; // siempre es bueno saber cuando fue creado, validar antiguedad
	
	@DynamoDBAttribute
	private boolean status; // estado Activo/Inactivo
	
	
}
