package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName= "customers")
public class Customer {
	
	@DynamoDBHashKey(attributeName =  "id_customer")
	@DynamoDBAutoGeneratedKey
	private String idCustomer;
	
	@DynamoDBAttribute
	private String dni;
	
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private String surname;
	
	@DynamoDBAttribute
	private String phone;
	
	@DynamoDBAttribute
	private int type; //queriendo implementar un tipo de manejo por categorias de clientes (preferencial,empresas, estandar, etc)
	
	@DynamoDBAttribute
	private Boolean status;
	
}