package com.example.demo.model;

import java.math.BigDecimal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName= "transactional")
public class Transactional {
	
	@DynamoDBHashKey(attributeName =  "id_trx")
	@DynamoDBAutoGeneratedKey
	private String id_trx;
	
	@DynamoDBAttribute
	@DynamoDBIndexHashKey(attributeName = "customerOrigin", globalSecondaryIndexName = "customerOriginIndex")
	private String customerOrigin;
	@DynamoDBAttribute
	private String customerDestination;
	
	@DynamoDBAttribute
	private BigDecimal amount;
	
	@DynamoDBAttribute
	private String time; //queriendo implementar un tipo de manejo por categorias de clientes (preferencial,empresas, estandar, etc)
	
	@DynamoDBAttribute
	private int status; //se puede manipular si estamos usando SQS 
	
}